version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    restart: on-failure
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/exampledb
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=admin
    depends_on:
      mysqldb:
        condition: service_healthy
    networks:
      - mynetwork
  mysqldb:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=exampledb
      - MYSQL_ROOT_PASSWORD=admin
    ports:
      - "3308:3306"
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
    networks:
      - mynetwork
      
networks:
  mynetwork:
    driver: bridge