version: '3'

services:
  calculator-backend:
    build: .
    ports:
      - "8080:8080"
    environment:
      MYSQL_URL: jdbc:mysql://localhost:3308/exampledb
      MYSQL_HOST: localhost
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: admin
      DATABASE_NAME: exampledb
      DATABASE_PORT: 3308
      DATABASE_DRIVER: com.mysql.cj.jdbc.Driver
      DATABASE_PLATFORM: org.hibernate.dialect.MySQL8Dialect
    depends_on:
      mysqldb:
        condition: service_healthy
  mysqldb:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: exampledb
    ports:
      - "3308:3306"
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]