spring:
  sql:
    init:
      platform: mysql
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/exampledb}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:admin}
    driver-class-name: ${DATABASE_DRIVER:com.mysql.cj.jdbc.Driver}
  jpa:
    properties:
      show-sql: true
      hibernate:
        dialect: ${DATABASE_PLATFORM:org.hibernate.dialect.MySQL8Dialect}
    hibernate:
      ddl-auto: update
  application:
    name: calculator-backend
server:
  port: 8080